// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"EQA/backend/app/controller"
	"EQA/backend/app/pkg/cloud/sqs"
	"EQA/backend/app/repository"
	"EQA/backend/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repository.UserRepositoryInit(gormDB)
	authServiceImpl := service.AuthServiceInit(userRepositoryImpl)
	authControllerImpl := controller.AuthControllerInit(authServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, authServiceImpl, authControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var sqsClient = wire.NewSet(sqs.NewSQS, wire.Bind(new(sqs.MessageClient), new(*sqs.SQS)))

var userRepoSet = wire.NewSet(repository.UserRepositoryInit, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)))

var authServiceSet = wire.NewSet(service.AuthServiceInit, wire.Bind(new(service.AuthService), new(*service.AuthServiceImpl)))

var authCtrlSet = wire.NewSet(controller.AuthControllerInit, wire.Bind(new(controller.AuthController), new(*controller.AuthControllerImpl)))
